Repository KohlsTechnology/eunomia, pull requests merged in 2020-06, with the labels that each got.

#345 Upgrade operator-sdk v0.12.0
  .github/RELEASE.md
  .travis.yml
  DEVELOPMENT.md
  Makefile
  README.md
  TROUBLESHOOTING.md
  cmd/manager/main.go
  deploy/crds/eunomia.kohls.io_gitopsconfigs_crd.yaml
  deploy/helm/eunomia-operator/templates/crd.yaml
  go.mod
  go.sum
  pkg/apis/eunomia/v1alpha1/gitopsconfig_types.go
  pkg/apis/eunomia/v1alpha1/register.go
  pkg/apis/eunomia/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eunomia/v1alpha1/zz_generated.openapi.go
  pkg/controller/gitopsconfig/controller.go
  pkg/controller/gitopsconfig/controller_test.go
  pkg/controller/gitopsconfig/init_test.go
  pkg/controller/gitopsconfig/jobwatch.go
  pkg/handler/handler.go
  pkg/util/util.go
  scripts/e2e-test.sh
  scripts/operator-sdk.docker
  scripts/operatorhub-deploy.sh
  scripts/run-eunomia-locally.sh
  test/e2e/util.go
Labels: team/kre, wip

#349 update deployment strategy to rolling update
  deploy/helm/eunomia-operator/templates/deployment.yaml
  scripts/e2e-test.sh
Labels: bug

#350 Resource deletion mode bug
  DEVELOPMENT.md
  template-processors/base/bin/resourceManager.sh
  test/e2e/issue311_test.go
Labels: team/kre
