Repository KohlsTechnology/eunomia, pull requests merged in 2021-03, with the labels that each got.

#384 Refactor into functions, add testing, and add namespace identifier to…
  template-processors/base/bin/appendResourceVersion.py
  template-processors/base/bin/test/test.json
  template-processors/base/bin/test/test.yaml
  template-processors/base/bin/test/test.yml
  template-processors/base/bin/test/test1.json
  template-processors/base/bin/test_append_resource_version.py
Labels: bug

#387 chore: update to go 1.15.8
  .travis.yml
Labels: cleanup

#388 deploy/helm: add option to create PodSecurityPolicy
  README.md
  deploy/helm/eunomia-operator/README.md
  deploy/helm/eunomia-operator/templates/clusterrole-operators.yaml
  deploy/helm/eunomia-operator/templates/podsecuritypolicy.yaml
  deploy/helm/eunomia-operator/values.yaml
Labels: enhancement
